# kubectl apply -f service.yml
# Servicio para el Backend (API)
apiVersion: v1
kind: Service
metadata:
  name: api-gpt-be
  namespace: danna
spec:
  type: NodePort  # Cambia a LoadBalancer si estás en un entorno de nube
  ports:
  - port: 30004       # Puerto que el Service expondrá
    targetPort: 8085   # Puerto en el contenedor donde tu aplicación escucha
    nodePort: 30004    # Puerto asignado en el nodo, opcional
  selector:
    app: api-gpt-be    # Debe coincidir con las etiquetas del Deployment del backend



---
# Servicio para el Frontend (API)
apiVersion: v1
kind: Service
metadata:
  name: api-gpt-frontend
  namespace: danna
spec:
  type: NodePort  # Cambia a LoadBalancer si estás en un entorno de nube
  ports:
  - port: 30001       # Puerto que el Service expondrá
    targetPort: 4200     # Puerto en el contenedor donde tu aplicación frontend escucha
    nodePort: 30001    # Puerto asignado en el nodo, opcional
  selector:
    app: api-gpt-frontend  # Debe coincidir con las etiquetas del Deployment del frontend